language: python

python:

  - "3.6"

script: 

  - python PythonProgram.py
notifications:
  email: Priyalguptaniec123@gmail.com
services:
  - docker
after_success:
  - docker build -t kirtigupta123/img1 .
  - docker images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push kirtigupta123/img1
