language: python

python:

  - "3.6"

script: 

  - python PythonProgram.py
notifications:
  email: Priyalguptaniec123@gmail.com
services:
  - docker
after_success:
  - docker build -t kirtigupta123/img2 .
  - docker images
  - echo "Priyal@123" | docker login -u "kirtigupta123" --password-stdin
  - docker push kirtigupta123/img2
  - docker pull kirtigupta123/img2
  - docker run -it --name mycontainer img2 /bin/bash
