language: python

python:

  - "3.6"

script: 

  - python PythonProgram.py
notifications:
  email: Priyalguptaniec123@gmail.com
services:
  - docker
before_install:
  - docker build -t kirtigup123/img1 .
  - docker run -d 127.0.0.1:80:4567 kirtigupta123/img1
