language: python

python:

  - "3.6"

script: 

  - python PythonProgram.py
notifications:
  email: Priyalguptaniec123@gmail.com
services:
  - docker
before_install:
  - docker build -t kirtigupta123/img2 .
  - docker images
  - echo "$DockerPass" | docker login -u "$DockerID" --password-stdin
  - docker run -it --name mycontainer1 kirtigupta123/img2 
  - docker push kirtigupta123/img2
  - docker pull kirtigupta123/img2
  - docker run -it --name mycontainer2 kirtigupta123/img2
deploy:
 - provider: heroku
   api_key: 7d3577f4-4234-4248-9790-3a4f9423f56f
